num=list(map(int,input("enter 5 integer no.").split()))
print(num)
l=len(num)-1
print(l)
m=l/2
print("The First number in the list is:\n",num[0])
print("The middle number in the list is:\n",num[int(m)])
print("The last number in the list is:\n",num[int(l)])
num.append(45)

print("List after appending an element:\n", num)
num.insert(1,50)
print("List after inserting an element:\n", num)
num.remove (45)
print("List after removing an element:\n",num )
num.pop()
print("List after poping an element:\n",num )
print("finding length of list:\n", len(num))
print("searching specific element in list:\n", 10 in num)
print("Repeat of an element:\n " ,num.count(50))
num.reverse()
print("List after reversing an element:\n", num)
print("list after reversing using slicing method:\n", num[::-1])
num.sort()
print("list after sorting in ascending order:\n",num)
print("list after sorting in descending order:\n", num[::-1])
