text=input("Enter any text:")
print("removal of leading and trailing spaces:",text.strip())
print("lowercase of text:", text.lower())
print("uppercase of text:", text.upper())
print("Capitalizing first character of text:", text.capitalize())
print("capitalizing first character of each word in text:", text.title())
t1=input("Enter the word to find:")
t2=input("Enter the word to replace:")
print("Replaced text is:",text.replace(t1,t2))
